port = 5432
host = '0.0.0.0'

print_db_statistics = true

max_connections = 350
max_locks_per_transaction = 64
max_wal_size = "1GB"
min_wal_size = "80MB"
wal_keep_size = 1600
checkpoint_timeout = "5min"
checkpoint_completion_target = 0.5

log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,client=%h %r (%x:%e)'
log_level = 'ERROR'
logging_collector = 'on'

[superuser]
name = 'admin'
password = 'admin'

# options for hot standby
[replication]
name = 'replication'
password = 'replication'
# note: lag_health_threshold is in bytes - default to 20MB
# this is just greater than 1 WAL segment
lag_health_threshold = 20480
# maximum lag time in seconds since log was last replayed before replica is eligible for a restart
max_replay_lag_before_restart_s = 180

[wal_archive]
enable = false
path = "/hab/svc/automate-ha-postgresql/data/archive"

[pg_dump]
enable = true
path = "/hab/svc/automate-ha-postgresql/data/pg_dump"

[ssl]
enable = true
tls_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
# server public cert used for ssl listener# server public cert used for ssl listener
ssl_cert = """-----BEGIN CERTIFICATE-----
MIIDRTCCAi0CCQDxocfAs3SsNDANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMjIw
MzE3MTYyMTE1WhcNMjUwMzE2MTYyMTE1WjBkMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZhZG1pbjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANBkHZKzAG3T6z8kZn5jpaJtMY5XSsi677xDUxzAn1tV
nb2WjXsGnq2BlgWsC4PhejeEPEabEv4VyF6ZsatvUE29T6r/T/BM7FqA2IYeMKwU
xEOC3OFaGMK5aDG3x0SbC3j+K3VnI3xcyBxBpWH6pJuZSDvoKigAM1jP1KzIYxqx
E8qGEDMdRaWqgCqY7vF4+W/KMuB9ZwbhAZ4vFLjdQdhLUC3wcC0kNvb7dU/n8RK4
sQHT3nCEXh3zvaQxxuo9F2AC6ltEtyWddV12U8CnT0AFoU5JI8EaWUGwlUQfCgMm
KhYT1hN1D54bU+HnS5iO6yW5W4XQJig7gljQZ9tZnpcCAwEAATANBgkqhkiG9w0B
AQsFAAOCAQEAf3DTwmD9rsBoKIrxdI3ubq0GWuSPk8KWew1W3sv7OlCHx70c0il4
ciDKlWKjzWLdSsO+g/HGWT5lBzvr8CRTnYfaKAG0gUSYJoPxzOBw/lQ2TSktq+RB
pxFOaw67zuCB7EdMly/eaF4Q1YpRn22yf3NiyFg1fqAcy5+5V5SWmKqALJmAV9eF
7lF65861/fERxxwHgrenMxVFWTjC7JSglD2dynwndnPFvI9YgF4fcIG8HddubV8k
3LaSl5nMd8LCPHISaV8p3sf/1Qtkm3rweql3GuGcLSQmide3mQxjTFFJebcCR2x5
NF482P3c0bUMajHjhobumwDQUxxPkoPahw==
-----END CERTIFICATE-----"""
# server private key
ssl_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQZB2SswBt0+s/
JGZ+Y6WibTGOV0rIuu+8Q1McwJ9bVZ29lo17Bp6tgZYFrAuD4Xo3hDxGmxL+Fche
mbGrb1BNvU+q/0/wTOxagNiGHjCsFMRDgtzhWhjCuWgxt8dEmwt4/it1ZyN8XMgc
QaVh+qSbmUg76CooADNYz9SsyGMasRPKhhAzHUWlqoAqmO7xePlvyjLgfWcG4QGe
LxS43UHYS1At8HAtJDb2+3VP5/ESuLEB095whF4d872kMcbqPRdgAupbRLclnXVd
dlPAp09ABaFOSSPBGllBsJVEHwoDJioWE9YTdQ+eG1Ph50uYjusluVuF0CYoO4JY
0GfbWZ6XAgMBAAECggEASBw8t4TFgzuvzdu0s8ubh0ctvMmsESXOy2Coo+xruFk6
Cl7MemPiCLwsw62zFmGxvwA9M1l6Cv5SpZmdh2svaJc3uD481TRpHTA0vMQ5p3JQ
L+RatohMxSUPTxT/GVhlcerR8wBLoT8h59U3e14WE9nIyyIdZFYdboAMYfW9hYBd
M+01RWHCPAwfGfArH7WZTsR3A4BloMlTOLM9PyILQeWq30sCIh0Tmd4heVISqIdX
Xd5nSKmMmAaJT9pxm//ExwW0UlPaZPXIT46O1UtO2Bjx5m1qQT/8viDd3P6XqK4v
7ovGgU+d5mqCA3VFipGIwESFw5N4N8nHdVh1IUg5IQKBgQDouAb5FJnFA2FG95VQ
WCA1TuI393HbZieq0MEzOvDmApvSTI3HRmdbyXybmCdPw7igGtXoKgY4PRXarIUO
OeycDjp2KpNDSJTi1xPCVkjIAyU3UG39A5kIwwRNFR7VC47T/k0LTovwyKc74nTQ
xFp3Ru3ny5BP94/y5QInsWbFKQKBgQDlPQyiXf0J29ps5lnfwejLqkRSgl8uJVpQ
B3JfzkKTX+nphDYwjbQCXFK4T2Jk6JGTXF9HOWlLljEoaOadY2ERJ1sCG8jycXPM
a3DgnfqCxjbtzYyTaw0n98e2ipFYwoO1xAT1BV3OmE993YtwSYw3hjvLalAjukyc
N91k95v9vwKBgCE+eLCIQtcj/nd20ruheyhiVmqMTJV86Fm8bHz3BIa3BK9sBCzd
X9J62/QWLjd0zCEC9F+v8SeDgmW0k2VO3QAGAE/1EQhhi/NDqizuyoLYAC8ArFWi
d/AKe8jPJZJljke2YiclV1RUNZ+WX/2arxmu5jlgmQLzaHrYQBCPhRDRAoGAIEOf
a5re6mxPKdSiAaRBJ6knRJWk39HSDEGAD4vwQt3VBlDdb6gCFfL4kYhayOkS1DLE
Fjo2X7Ub5hwdmTlLiCaJ4JoYhkcBjVvx3ytc/tr3EDFF/9mpWF6/dSm7m0qFTyfv
qqy+rz0wsv5jicJQQeBauh6UePLXpYUXXAadpfECgYAODuedu+lK6QswIIUckX0f
DvoUpPE75jytiPPr6kIqf98eNzPd8VzDXw4EJRgIdTBheheJVbuLDx7++mqr5mq+
6NGDsAxQlve0C5NHo6ERnG2RJIpeeA3Xy5mRsWXH7lyZM9eoqH5AoEisgDLs57RI
NGjt3hU5U0R7ao9gjTT6Iw==
-----END PRIVATE KEY-----"""
# issuer public cert that signed the above server public cert
issuer_cert = """-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAK1fSCOS4S+nMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yMjAzMTcxNjIxMTVaFw0yNTAzMTYxNjIxMTVaMGUxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBALKx4HRXXc2rVlwagrXByQLYJLGBSuwz1j0U
uzvH0GoXGcZsnEUgPBK1KyD/cOQlayuG1KtgiuW/iO8u2fs8rGcYvo+8nVO67vgO
d1PFxpZbo53MZ82MK255B4R0ahU2a2LggJvYT4GojMBWm+MwgtB1YS+wLpBwKPzk
x3cbqzUzewHm0WIbHZPuqWph4xjaE+bkL/imqYY6ie6udZ786REfQNKYQh25NmMT
3wCvGOEAEfabqgZMEY3JBrnIvEJym1VGFZ8qKa1HJ8XeARWJKLKUY7D6/Ye4zW2t
kozr4l42Je/jSs/PSnD7jWCcSMhDvhSTrko3K+9ZQqryd5hFtk0CAwEAAaNQME4w
HQYDVR0OBBYEFAVfiL3XpuPhkyjWpGLhKGMXqgZ8MB8GA1UdIwQYMBaAFAVfiL3X
puPhkyjWpGLhKGMXqgZ8MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AETIiNNGIYTT/d3+/oF7OP/XZflDbM4jQ3BDNHsES6NljlYxe4a2fjiitPmSGiF4
jNB15KIwuPIWboZ5Qc3xiZXiozlT/H1OMgqZCushB3KYzVZDo5antYsUoTFHBK3G
1K7Zil9IWzwNOtzFsBSkJQrpDNZKbgaz9t1WtjPbRiBBxBfIKrchUije9SmgX4MQ
YG1km6nDmX0+v87WsnhT/vvbuGskusp9naCd2q0dVF5KXpwX83WrhuJKgX+RIKJx
BJikzdBZwRto4cbfaOLAriQX8iJqhX0K21jlxCR7IX3hHj13TBWc6SYlyo7tlFEo
3iNelyX+GNK+cNG98Q4sfPM=
-----END CERTIFICATE-----"""
