port = 5432
host = '0.0.0.0'

print_db_statistics = true

max_connections = 350
max_locks_per_transaction = 64
max_wal_size = "1GB"
min_wal_size = "80MB"
wal_keep_size = 1600
checkpoint_timeout = "5min"
checkpoint_completion_target = 0.5

log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,client=%h %r (%x:%e)'
log_level = 'ERROR'
logging_collector = 'on'

[superuser]
name = 'admin'
password = 'admin'

# options for hot standby
[replication]
name = 'replication'
password = 'replication'
# note: lag_health_threshold is in bytes - default to 20MB
# this is just greater than 1 WAL segment
lag_health_threshold = 20480
# maximum lag time in seconds since log was last replayed before replica is eligible for a restart
max_replay_lag_before_restart_s = 180

[wal_archive]
enable = false
path = "/hab/svc/automate-ha-postgresql/data/archive"

[pg_dump]
enable = true
path = "/hab/svc/automate-ha-postgresql/data/pg_dump"

[ssl]
enable = true
# tls 1.2 ciphersuite (to exclude tlsv1 and tlsv1.1)
tls_ciphers = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
# server public cert used for ssl listener
ssl_cert = """-----BEGIN CERTIFICATE-----
MIIDRTCCAi0CCQC92hQxziBQnTANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMjIw
MzE0MDY0MjE0WhcNMjUwMzEzMDY0MjE0WjBkMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZhZG1pbjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANia++LXysA0ulwjbvNq6pgewPr1R4Eh/ZxQFWwnqkX5
3pYWSl+IRYxNJAO2JKTRQiiM6GFBwc7df2+jgoZnzAduBarOp5BLVTWRW3MY3NcJ
SAfACZAb0Y0S94xwhu5mYlAoIZLiCWqfCBksPIRAy7qcWbqE9+VEVXsSam6EbfvG
W2Y7rAsgF4Qbm9g1ZXI5RfM8AxsX+wnAQmHXvbs+SdZL7sObe3QEI0c3bSx8Ii8k
L5FBqbPCFvqdVEm0VET/bDmcFGAwTIybPyvZ95O1ggy753+Waw4R2Fs8Gn9cHa+z
cM3S09NljmbduCYbQm9PYquPmdAht/hZqvwyEKW5fHUCAwEAATANBgkqhkiG9w0B
AQsFAAOCAQEAESmeHKsI640HkVjAcBFZ3pJxf9Z8n0DU06eFsbfVZwOr8o6mzf6O
11ijZdKNXlYEt2CNqphY7HGrB/WMoOyKobHROv1kjoD1zWrk8cCjzDRH9hDIfFyh
6w0DtK4nelVnj1WjBz4qbmY7BKxgU+V5gAXaiInNhhe5TCiSIZrkNdUpRTPq9y2Q
z3rKuo/YX9IBG9zczEi7r3mOGk+k5JHfqB7Px+feYlzFU05EDZom8GKfGYMznnY3
3pJxzxX3QgQo9ch+JKHRsNmQ8MAJ9Qr9wGVIUwxQ6DyS1gbdOoeo354BhrEAlQSq
3u7bgeoTcjdckMWJkWQT1Yi/AZ70bKQtAQ==
-----END CERTIFICATE-----"""
# server private key
ssl_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYmvvi18rANLpc
I27zauqYHsD69UeBIf2cUBVsJ6pF+d6WFkpfiEWMTSQDtiSk0UIojOhhQcHO3X9v
o4KGZ8wHbgWqzqeQS1U1kVtzGNzXCUgHwAmQG9GNEveMcIbuZmJQKCGS4glqnwgZ
LDyEQMu6nFm6hPflRFV7EmpuhG37xltmO6wLIBeEG5vYNWVyOUXzPAMbF/sJwEJh
1727PknWS+7Dm3t0BCNHN20sfCIvJC+RQamzwhb6nVRJtFRE/2w5nBRgMEyMmz8r
2feTtYIMu+d/lmsOEdhbPBp/XB2vs3DN0tPTZY5m3bgmG0JvT2Krj5nQIbf4War8
MhCluXx1AgMBAAECggEAJHH3XdS3PZ3hmW0w1u4vaMcL623nyReCB5IF+Lu3z6xa
QmCfxPE12oSEQcec5Mp82jvTQcIBrR/huFQHuzutvbZKZ9H7qbCzNp8thvEw/1GF
eCBcu42itZzyYAPzABvkAN6vv3oe4Xy+rRWfXRVV8iEqi9Khr0bPJzUTCWNo6grH
vFT73uX2qOF3V9GUsOdNYfnV1Tq9ElnijqDYXHgDRu+9cTVATpHkS20Z47Y2BFuo
+FglSuL6fegfXi+ZOn1I4t0lcdLFo0aDW4p31q3fzBJY7yfxCYfUQxRI4cpQ2iIU
q2VXObiFycZHesADd4gcApDqB2vHs5pgmXvjiMuFYQKBgQD0QYwgrqo/+tqYyJ0y
RS8WD2N4AN3wZ4cznjUlboTUkWU0mO0kqKCQEd6fi/1E+ibd1KmCq7uJV1V/PVpT
fTze42veM0JSsrI8uZjJoSOLoD+YSUoxL+w1z1/IeAWbR60NK/saP8/+70kbLTmj
24ar8ko5DchcyVahqxG5wSl6+QKBgQDjBRh5jrP6P08TVBsf9xwaXNFrqrVPZYm2
F2Ng8jKUnJBDU5giAYvzSny73wlUPn4FDhQz3nCeAfCsh5TeWW1FnqrImRBBQwEd
s0k0DMOiGv62TTD9T2WBmvYdMBmlYc4AsufwM6Ov3pBhy2nYKbKrYPXH1EybnyRe
l297QYpQXQKBgQDFINGS3uSQVkht3hrgI23pA+pnQ2vbRfKb+icyWovhcqaXWISr
fVx4abOeWEDDlpAfoC5eQ3NLWKyr0DxB/WVPDYRVBFGWpJms4K0qrV4epeotYZj7
MY4Vr5PCGvuLYsGLS9+QQ8f+G+iIgmtujxGVXCoC+dim6ed8+q+Hlxl/IQKBgFiV
s3AzfA1JSOzs48y8Wy36TAmsSiWaJHt2cuPwfkY5NZ3f77xNSDP+O9//bx99ZyVH
0iBPSziM30IjgbalxJrnCBNQjuQ4ZiYVwJnb5TbLO9sdEeG2apCBTEola8x59q2V
IiY7sEK/IS3X9wxPcRWotx9ruxz6o3F5vBmngHZNAoGAeSsuRJyiruIwUya5kRFT
rMzKtWY2j2knHtNFS5dEdYI3+gQHlHwias5hWDe8cRBIodcCfGKmqxKR2EbPtSGP
cmRnnRddJ8HXDiI8ID1VdHEGprjt3KUQmhJ/EkdHMZ+WSrne/2NffYNH4PXdO0V6
3Cffgavh+wZGfjidz8E2cA8=
-----END PRIVATE KEY-----"""
# issuer public cert that signed the above server public cert
issuer_cert = """-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAOlmPP8hypjuMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yMjAzMTQwNjQyMTRaFw0yNTAzMTMwNjQyMTRaMGUxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAJp1N7CEhqhik0YWLCebZK+oJtKZkLQBgAJp
ncgwKwQ/r3jmdKwIZYbdW80kjGeI8KPh74tHAhb0xyUSQEYTNMKiYuXN8jrEHaM0
xQrCQD8ZEBhzvfN86yIPdqNrrnPncm4KIZzox0EG+g/yqfygQ29BoCwYe7SUOI+u
0dGpj26Q6tpi8Ape837/a9uv1037lM6ejSkBkB8LVyy2mA3YCbNnFizAKjXMx1ov
eEmb/O2h7jKz/Vq1vZzh6NSS6dhaLH2ioIhKjZrRMyxqLkyfKWV5Gon34h+TngmQ
vTienEQPP0AvfdGXrtVa89MFOUOVLJVB1w+6Dr2nyhDq5vofaQcCAwEAAaNQME4w
HQYDVR0OBBYEFFetK+p6PpPbXu5yJr/lm5jUyCmcMB8GA1UdIwQYMBaAFFetK+p6
PpPbXu5yJr/lm5jUyCmcMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AJGGUPpWR+OF6YG2r7nLahS3FjK54ZUGfn5UQhKni7Pk44+1MgnzwiPh9Nk5ydhf
e9XfPoT21RGqH0k2c8mlRQk8JT6m/am7MaUwjl1nY8H0xT4E96wbn7ENkOJpkoPP
tvPRhdM36wY8k0WBAS4EJ1DFbuPi9aP2tAFT2Kcj74EgKT5vqffPqNVUmnJI1Y10
cJAz3Im/rzB6Hau6cTx+h7hnphjNc8ay9Gnuqm7xjClzh3/SOtZm7wBeNH842iGf
VbpKd6c594YqXP6sDHiHJBHhnnAumkfm0WxVs1FF/k2ULDLQUPbKt8fas6RMAVZL
tHC7vSOu6OOUM9OlFIc0yGI=
-----END CERTIFICATE-----"""
