# ======================== Elasticsearch Configuration =========================
# The es_yaml top level key contains whatever data will be written to elasticsearch.yml
#
[es_yaml]
  [es_yaml.bootstrap]
    memory_lock = false  #true

  [es_yaml.cluster]
    name = "chef-insights"
    [es_yaml.cluster.routing.allocation.disk.watermark]
      low = "85%"
      high = "90%"
      flood_stage = "95%"

  [es_yaml.discovery.zen]
    minimum_master_nodes = 1

  [es_yaml.http]
    port = 9200

  [es_yaml.transport.tcp]
    port = 9300

  [es_yaml.indices.recovery]
    max_bytes_per_sec = "250mb"

  [es_yaml.network]
    host = "0.0.0.0"

  [es_yaml.node]
    max_local_storage_nodes = 1

  [es_yaml.path]
    data = "/hab/svc/automate-ha-elasticsearch/data"
    logs = "/hab/svc/automate-ha-elasticsearch/logs"

  [es_yaml.opendistro_security]
    enable_snapshot_restore_privilege = true
    check_snapshot_restore_write_privileges = true
    # These are the dns we use for our generated certificates. Override if you're generating your own
    nodes_dn = [ "CN=chefnode,O=Chef Software Inc,L=Seattle,ST=Washington,C=US" ]
    [es_yaml.opendistro_security.authcz]
      admin_dn = [ "CN=chefadmin,O=Chef Software Inc,L=Seattle,ST=Washington,C=US" ]
    [es_yaml.opendistro_security.ssl]
      [es_yaml.opendistro_security.ssl.http]
        enabled = true
        pemcert_filepath = "certificates/odfe-ssl.pem"
        pemkey_filepath = "certificates/odfe-ssl.key"
        pemtrustedcas_filepath = "certificates/MyRootCA.pem"

        enabled_ciphers = [
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        ]
        enabled_protocols = [
          "TLSv1.2"
        ]

      [es_yaml.opendistro_security.ssl.transport]
        enabled = true
        pemcert_filepath = "certificates/odfe-ssl.pem"
        pemkey_filepath = "certificates/odfe-ssl.key"
        pemtrustedcas_filepath = "certificates/MyRootCA.pem"
        enforce_hostname_verification = false

# Runtime settings for jvm.options and the systemd service
[runtime]
  max_open_files = ""
  max_locked_memory = ""
  es_startup_sleep_time = ""
  # This config variable becomes the value of ES_JAVA_OPTS.
  # Note: JVM values for -Xms and -Xmx are auto calculated in the run hook.
  # Any value defined here will override the calculation in the hook.
  es_java_opts = ""
  # It looks like the default NewRatio is ignored when setting UseConcMarkSweepGC
  # https://bugs.openjdk.java.net/browse/JDK-8153578. If we set it explicitly we
  # can get the expected behavior
  new_ratio = 2

# This section contains any settings that need to applied on startup for opendistro.
# Any values put under this hash will be rendered into yaml and applied with
# securityadmin.sh. These should be your basic admin credentials, as long term you
# can manage your creds outside of habitat with securityadmin.sh.

[opendistro_auth]
  admin_username = "admin"
  admin_password = "admin"
  dashboard_username = "kibana"
  dashboard_password = "kibana"

# Fill these in in your user.toml to override automatic SSL Cert generation
[opendistro_ssl]

# root pem cert that signed the two cert/key pairs below
rootCA = """-----BEGIN CERTIFICATE-----
MIIDnTCCAoWgAwIBAgIJAKwv5Cmw3F+gMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRow
GAYDVQQKDBFDaGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTAe
Fw0yMTEyMjgwNTEzNDFaFw0yMjAxMjcwNTEzNDFaMGUxCzAJBgNVBAYTAlVTMRMw
EQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMRowGAYDVQQKDBFD
aGVmIFNvZnR3YXJlIEluYzETMBEGA1UEAwwKY2hlZnJvb3RjYTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBALDaWlSMZLvyceAXZGzgmQSnOaLQYWWcWib8
uEQq5XegdHfqwwIgP1QtullmO9nPMeIlOaeibMXuo6WGWHuDkzZ7b9UQWpFtuEsx
BsgkZQ+VKcuiMSgvd+tQPWnI1mDcJypJmOGXM8l40MiIeMFieib0qY60ua/s+QKU
voJowIRlIbg5m7sc8PEBEJErI1+iveQG6MmkxYedCgy9QSqTq8/C042IB7wIVFE6
/JGJZpntqquCtRkx3j87lYwwswhmtz1k5z9QoNpzCZPJZ1ROi5jIsE40F/QZAG2F
6hU/IANCEOVQkmqX4NzFE9MJ/PGzGVHXZ2xvYrWcyTXMMz5wrGECAwEAAaNQME4w
HQYDVR0OBBYEFBVI/8n/i5e6CNeI5GAZE8g1YUudMB8GA1UdIwQYMBaAFBVI/8n/
i5e6CNeI5GAZE8g1YUudMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
ACiAIDPj9Tmf/aL7yCLj3iNh/7McdPa9F8u1HD4Yb9d+NTIdA4DpuE+kBMHfVxRy
Lcdc+KW+JEIdWcRErUtndDIAyh3nUTYfjlS2LMdzpLzQ7a3NUC5Bia6mlG+F6TPy
/ssPErKFe02whi6wz30/9LdMpp0M1FtTGH9sk34h8g32vEaLxagkgNUCiLK9v3eL
HMICUObwYSyvpRhKA5RhTVn2OoIZTAnUWdRcMAMajtkq4Qe0BSi+VCpcAwILKbNa
6YIoiTw+zw1t2HvVME6IVFU30mYG80KrbYn7b/Ok1AsTYhh3DqwEUO9CV1BM/lmB
cF99F/2DE5y0TgI52hM6HzI=
-----END CERTIFICATE-----"""
# Certificate used for admin actions against https://9200
admin_cert = """-----BEGIN CERTIFICATE-----
MIIDRTCCAi0CCQD8aa/L1KuudjANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMjEx
MjI4MDUxMzQxWhcNMjIwMTI3MDUxMzQxWjBkMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxEjAQBgNVBAMMCWNoZWZhZG1pbjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAKY9l45rKiUHl7pkCZYcUS7CeU17dqQHPJmIZVIKE4pj
BKVzBsi1jrPfLooEdFS22thtIY3cWjZYjmKjc4KCNZsoCIL/qIlib6WEqBGOLksM
01NubaRUJHXVDta00zqGPY5h6/JYRjxUgNPgiEjVrQPYmRO4wz2++I64SgZ14x9+
uNcMb72gbegdFU0UTnJgZBKzpglIeG6soR6CVpyzKtRSPJ14z6AEiEuGRKomMS92
uO6KHkPtcLLLeCgFbXFXGe+pUtMBg8ztGi+009dsqWZgZJidEyu2Yqd/xDs/sB60
wJotc5X+tkSw2b6GJlBDPaca8Nrz7I4lCyBsMv67YN0CAwEAATANBgkqhkiG9w0B
AQsFAAOCAQEAjJiROnvme7fXaOsdOXVV/uzvWhS2AAVgdtC+WzjHvpA3KMPtrhgA
IGGM/icFBDQhjyJn/MM1sejaUw3ostMhZtaPDmzYfW+6/7M/VNxI/U23UB/MUapA
USDMnQL/XU6mmtCxpEmjWyonflCnhzsjOkUmg+60xbDvTs1GIUD3xHlfG9K3WOZi
EsZGv5X4oidrM+XAlyFrn2M4hORMYkNOPlce6AGaQyLuJeYNrZiLQpTbS+XPjkLZ
zxRVpiYUOzQfKrfR7Xf/BfFgeWbeuUngABSove9vKschQN1rQL5+zmTnuk7hml1X
0FbyDeuNoDugvKgQyneQtzoF7ZMeJRN/Tw==
-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
admin_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmPZeOayolB5e6
ZAmWHFEuwnlNe3akBzyZiGVSChOKYwSlcwbItY6z3y6KBHRUttrYbSGN3Fo2WI5i
o3OCgjWbKAiC/6iJYm+lhKgRji5LDNNTbm2kVCR11Q7WtNM6hj2OYevyWEY8VIDT
4IhI1a0D2JkTuMM9vviOuEoGdeMffrjXDG+9oG3oHRVNFE5yYGQSs6YJSHhurKEe
glacsyrUUjydeM+gBIhLhkSqJjEvdrjuih5D7XCyy3goBW1xVxnvqVLTAYPM7Rov
tNPXbKlmYGSYnRMrtmKnf8Q7P7AetMCaLXOV/rZEsNm+hiZQQz2nGvDa8+yOJQsg
bDL+u2DdAgMBAAECggEANcFk6KCumBrEbXk7wFaXyc8I+o0Z6CCO7/azDLxFZVJv
hjCT2QMcif15Rxf5pgsa6TEg0IaYhUpNgIfqKiGAxBNF7VZOYV57S8KBtmuLfKlB
DJGA0sqCn7etfLAsPZh6/zea3Fq/G3MX1Wudpi+yKrQ3i7ELMUQ3i678AOrN7ri9
9lhQvXZsKfC8yyparsEUIGIv4MXlUuofFEj6+Fbc1Dh3nSelPAhWAXJsj4P74zd/
fM42PByKizBXqg21zQ5abSylZr9LBLRH+BwkLoUhXXrqws9Lt6CNK7ZdDrCWcVKT
0UxNAmaYNr4J5k/LcaxYLxvvg2c+s/Odhim90bLY4QKBgQDWvbZ06bd0T7RsTs9b
K4mag+loIJxgO8iC1R8mJ/9K8C0t5tGvMpsqkOhj9pdbaxGvS8Mle7Ho4tR6LLj6
/ga0a1EKXjcKoEA3cq/pQPPpJnz56HXzUNn+U48JRxMEORWADIsEzr+f0O+vJ0c0
3YnGiGPsyMoEe/dVTHZR7OWxDwKBgQDGLlPdYRyPrFqpn2EAgMcYyPzgzv4qQr8t
enrgCQX00ysyNYzohl/GLO/aTLnlPUAvXsUyD882iorRNVCB+eI7oQ7m57xwbbkB
g3f2if0/ApETi8qPlYSuZkJhyluTnf/Ujy3nsOEGcSqX1p8UOIyyzUtHVy4JX48z
00r4m7t3UwKBgENlrZNKG0sFDRKFNa1en8SALEyDF7FYchkl/K3EFesWMIfcjukW
z/5vFpDxPxXxJ87Fz4y/Itp9/sQNr00PV1le6UOAyHOsUhtVAoMJ4MPHUag53nMs
aA7beOQni39izy2uQh+TKC9nqyJlCIM+GNTXz8zsRANeSQVbhzM1T+3fAoGANwCy
m/WQ5Ls0KnGmjWowV8uoi4hHeFkwECI3Kii2830MNxIvunVY7XqZUyAKU/pM7xjB
aCSFISEQaAIBByHgTSZlKWbVoOqC902SpOUlWTCQLTmWDYW03mZZNCTih7TJRSg7
2Fr6CTytUpjpa8ZKHnHl27Xxe/5+kyaoXxlxzSsCgYBJprB0YN0vnLKMAohLk8vS
euIK9Yztq+nSqJ3W+DYFgEGVaLME+DXsMuSqlRYSrjunaT4egpQODxO6O8Xrb7Mk
2INvMFYCluUdjiy5pSVAzVZ31Tdx6wpLfHaKU+m9ME10Z9t4iAVbLAK8sRlKbFS1
zs9Ww/6/uJFgJrUHjsDjVA==
-----END PRIVATE KEY-----"""
# Certificate used for intracluster ssl on port 9300
ssl_cert = """-----BEGIN CERTIFICATE-----
MIIDRDCCAiwCCQD8aa/L1KuudzANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJV
UzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UE
CgwRQ2hlZiBTb2Z0d2FyZSBJbmMxEzARBgNVBAMMCmNoZWZyb290Y2EwHhcNMjEx
MjI4MDUxMzQxWhcNMjIwMTI3MDUxMzQxWjBjMQswCQYDVQQGEwJVUzETMBEGA1UE
CAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEaMBgGA1UECgwRQ2hlZiBT
b2Z0d2FyZSBJbmMxETAPBgNVBAMMCGNoZWZub2RlMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEApvGIS19mDBMLiCOAQ1fzOnrM3KmTDLnoXqDeu8AMbFmJ
o2QVyyyVpeVnQG8lE0NehpTeFrR4+3Zc0ILbxa371mJh59FDIysro5yIbxWnrnvX
UXmS+uNaJz93+0Mfj0oVYfdg3GcpuEW402qaMaRV2I5JQ3D0nAWwqO3x9bE5Skj6
KNhFE3vIxGnJ8Pduhyl4LXTiwGo1d5LXR7+pN0HLAFgMxTegWZ1j2W3/Sv0glYiq
FJ2A1KcuXjOtvFU+dkYP/GPlUz/HnQoK5ZtLv+H9kVVWvPl9ochsrTiXiNeHt2kg
flM16955bRc7siuITEHst/wxB+JwklApePMuiU6MtwIDAQABMA0GCSqGSIb3DQEB
CwUAA4IBAQA1yjaF6eEYDtsaaZsCWg61JAmhXjWdEzEddNLuN7ABIiK3jRFrbT70
ZvuMBHbNfbMfLw6R1yjbdPxqCuO8SRlOBdbtYd+TvhkTdeGqWgvCSzO/i1QhZ4p9
2FOiK0ci1p0noGY7V1DWks/wIMV5Xt0SNVN8XjIjj7UpRvSdriZwgXeKqGaoTy18
T2870NH+v4S2Gk8AKDNvFZ0811h+QswnZw3ALrumYFidzT1Zgc609TybcOLd3fw3
PJt/EF8OMef7cqz1AC8ai5vinMqpUpzoKxRbkaiDEbb9JKuZx2GHaVbANRvhJhB7
No2GtLRVnxrVEzAwDJDRbcWlfqbQ0sDu
-----END CERTIFICATE-----"""
# the private key associated with the above pem cert
ssl_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCm8YhLX2YMEwuI
I4BDV/M6eszcqZMMueheoN67wAxsWYmjZBXLLJWl5WdAbyUTQ16GlN4WtHj7dlzQ
gtvFrfvWYmHn0UMjKyujnIhvFaeue9dReZL641onP3f7Qx+PShVh92DcZym4RbjT
apoxpFXYjklDcPScBbCo7fH1sTlKSPoo2EUTe8jEacnw926HKXgtdOLAajV3ktdH
v6k3QcsAWAzFN6BZnWPZbf9K/SCViKoUnYDUpy5eM628VT52Rg/8Y+VTP8edCgrl
m0u/4f2RVVa8+X2hyGytOJeI14e3aSB+UzXr3nltFzuyK4hMQey3/DEH4nCSUCl4
8y6JToy3AgMBAAECggEAEJ0UzTtvMmBq01+FEi6cfANgg800Xx3ZLCGiSNjx4459
jg8VxCRpuBq+TcFB1UrtC0OhXm0TZSMAVZfQOzn3R/x+dc1zevp+20dmpHdpOooE
gY0xvVoGzMUaMZ0adO4QdrFhqE1z72yw2glP0wThri1qyRViomxGimkznRnH88Zq
SPQS8z9IhNkDWlI893jQ9/FGiYNpUsWtPh8SVIoKFkP3mQ7YZhYXNQWbe2VoG0Gp
hTPFqiPwGs6GmYRVx62ZhvYVM85Y2gIwpzbohQDNa0/urZgM98sEqOWNHmmiRJ8A
5UozoBI8yc5q3fLtn9TxOvbO/mSUkEVGJQHvraDeEQKBgQDQNbyk7BAEXL+hOBhZ
JRdyIAzhHgjgaNkc4zAZoqkau13FndXZ8wAaci1jg74T7pvTh8A8V+VG0NQ1Efes
J8lHvzeP1Ie0YwtQkTgA9HWcfLTEB3WCu9XqwflJm15Imu9jYs1Hg97YC698alRu
4cE/Rcx8yXAf51GK2oPUjMenRQKBgQDNQwKqTr34Nk3o2K5wdWQK48oyCj4NJB4i
LrHtfGcg1N9bSfwORgQncjX9ogAwB/bvPrPctYf1kzxnUIVSZ3nUir/+H/ukDTUG
vKhivd5tovrGJb86aemKUnicgtYW6EyePn4fngOtyEaruAehlv3tbhpGNpznrOKT
2lR59FdVywKBgECU6nadYjp4Klhvdd3wy1zy5AvPrSEuZGm5bmoFMj7Ab02kr3hz
D00krT941bSJBnyOVupguRVGIQx1DkWv8Zb3kNxkJ9OkBRZwdNaW/QQVClzjk2eB
q9Ctag2Sy6PpqudA9juAg9aviTcmJBpgm/hsRglO0iCTN4/CR7HeGO+hAoGAWha7
KLx+rF5JO5U+mqUrT4xCxkuwiFv9zcro1O7w5HwJvCtwsWMRl66M+9EKfApC2yaO
EqSqE6KXtFCm80/vLNXpBkRLUelqCJbs4MmswjnyDt2qXJz3n3oq7aaPCGbUme+b
s4zK2I86VUvkLYvzzy2v4nk9zIEYwQPmZ9BSNJkCgYEAqFaZO5oBMmdjHRJgJs5g
+PKjjY6AjUuR3RCxBFN5irJrqsAyN4f/48Vk3crYE6yt0DHYNmf0v+Sn1TLaeSYv
hJemdcIDDJphMc4Px1Zr9CajWLDpY4y80DXvGdIY8FTjGRVK+Xgws8+edqwB6HVs
OpU0b9l9P7NhYdG6wZokrZ8=
-----END PRIVATE KEY-----"""
