[architecture]
  [architecture.existing_infra]
    ssh_user = "ubuntu"
    ssh_group_name = "custom"
    ssh_key_file = "~/.ssh/A2HA.pem"
    ssh_port = "22"
    secrets_key_file = "/hab/a2_deploy_workspace/secrets.key"
    secrets_store_file = "/hab/a2_deploy_workspace/secrets.json"
    architecture = "existing_nodes"
    workspace_path = "workspace_path"
    backup_mount = "/mnt/automate_backups"
    backup_config = "object_storage"

[object_storage]
  [object_storage.config]
    bucket_name = "automate"
    access_key = "SFSKJLKJLKJSDFSDLSKD"
    secret_key = "sdfsdlfksdjlkfjsdklfjsdklksjldfjlesdfsjl"
    endpoint = "ap-south-1"
